### ISSUE TITLE
Plot distribution of ancestor spans

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer-qc#19]
For a given node u, its span is the width of genome where its a child (lets ignore trapped ancestral material)

```python
child_edges = ts.edges_child == u
left = np.min(ts.edges_left[child_edges])
right = np.max(ts.edges_right[child_edges])
span = right - left
```

Plot the

1. Histogram for all non sample nodes
2. Scatter plot of span vs node time.

**Comment by savitakartik** [comment]
completed in #61
