### ISSUE TITLE
Polytomy score

### ISSUE THREAD

**Issue by gtsambos** [tskit-dev/tsinfer-qc#2]
Here's a simple function for calculating the *polytomy score* of a tree, which is a measure of how many polytomies are in the tree. It basically just compares the count of edges in the tree to the corresponding count in a binary tree with the same number of leaves. `x` is the number of edges in the tree, `n` is the number of leaf nodes.

```python
def poly_frac(x, n):
    assert n > 2
    return float((x - n)/(n - 2))
```
It ranges between 0 and 1, with fewer polytomies -> higher score. The score is 0 iff the tree is just one big star-shaped tree; in this case, there is one edge leading from each sample up to the common root node, so there are `x=n` edges. Conversely, if there are no polytomies (ie. the tree is perfectly binary), the score will be 1, as there are `x=2n-2` edges.

<img width="967" alt="Screen Shot 2023-04-05 at 12 59 04 pm" src="https://user-images.githubusercontent.com/17755074/230194189-b338744a-8662-4b86-8944-83adc1307789.png">

**Comment by gtsambos** [comment]
(btw, I was assuming that we were working with single-rooted trees here)

**Comment by jeromekelleher** [comment]
Is this implemented now @savitakartik ?

**Comment by savitakartik** [comment]
Yes, implemented now as Thanks, @gtsambos!

**Comment by savitakartik** [comment]
Yes, now implemented in `utils.py` and can be used like this: 
```python
import utils
tinfo = utils.TreeInfo(ts, chr)
tinfo.plot_polytomy_fractions(window_size, overlap)
```
Thanks, @gtsambos !
