### ISSUE TITLE
Somewhere to view plot examples, without running code?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer-qc#26]
Is there somewhere we can see examples of each of the plots that are produced (could just be a PNG in an issue)? Or do we have to run the `qc-template.md` code by ourselves?

I find it helpful for discussion purposes to have a source for viz where everyone is sure they are talking about the same plot.

**Comment by hyanwong** [comment]
Eventually I assume this would turn into a "showcase" so that people can see what's available.

**Comment by duncanMR** [comment]
I think it would be nice to at least include some example plots in the repo's readme once we've got them all working. Eventually, perhaps we'd want full documentation with image examples on tskit.dev?

**Comment by jeromekelleher** [comment]
We're still figuring out how things fit together, so showcasing is premature. Agree we'll want to do this once we have a good prototype though

**Comment by hyanwong** [comment]
Yeah, public showcasing is premature, but it's useful to have prototype plots in front of us to discuss between ourselves (or in GH issues)

**Comment by jeromekelleher** [comment]
Not relevant now we're going with the panel app architecture
