### ISSUE TITLE
Sample size independence

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer-qc#28]
We probably want to construct plots so that patterns spotted in them are independent of the sample size. It is probably worthwhile trying the various plots out with simple simulations using sample sizes of 10, 100, 1000, 10,000, and 100,000, just to check that different patterns are not simply a feature of the sample size.

**Comment by duncanMR** [comment]
I agree, that would be very helpful. As I mentioned in the meeting, I think it would also be useful to check what happens when we introduce sequencing/phasing errors. Perhaps we could also do it with real data, e.g. from the unified genealogy paper.

**Comment by jeromekelleher** [comment]
I don't think we want this for the initial version. Would it make sense for SARS-Cov-2 ARGs? The intuitions here are firmly rooted in the coalescent, so could well be misleading outside of that setting.

The coal here is to present the information in the supplied tree sequence without prejudice towards any particular model or species.

**Comment by hyanwong** [comment]
Sorry, maybe I put that wrong. I don't mean sample independence under a coalescent assumption, but something much more wooly. I'm thinking, for example, of the plot of mutation times. As we take more samples, *under any model* (pretty much), we start finding the rarer mutations. In this case, I suggested weighting the mutation time by the number of samples in a histogram.

We can test the (relative) sample non-independence of any plots by taking a large inferred tree sequence (e.g. the sc2ts one), and randomly subsampling it. If we create a plot with the subsample, and it is radically different in conclusion from the original plot, we should think about whether there is an alternative metric of weighting that would alleviate this.

So, I think this should probably be left open, as a reminder?

**Comment by jeromekelleher** [comment]
I think we want to keep the plots as simple and descriptive as possible, until we find a clear example where this isn't working and being misleading.
