### ISSUE TITLE
making plots interactive

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsinfer-qc#29]
As @jeromekelleher suggests, it would be good to make the qc plots interactive, as we can then examine specific regions more easily. @benjeffery suggests Bokeh as it is embeddable in a notebook. (We'd need to make sure that millions of data points can be handled, for example if we wanted to plot the number of mutations per site along the chr2q trees from the Unified Genealogies dataset, that would be ~5M sites.)

**Comment by jeromekelleher** [comment]
We've explored using panel for this in #31 and #33 and decided to go with it.
