### ISSUE TITLE
Add more fields to mutation data frame

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer-qc#38]
Only the most basic data was added to the mutation data frame in #37, we want many more fields. We can adopt a lot of the stuff in sc2ts [here](https://github.com/jeromekelleher/sc2ts/blob/c6180696b7dd51a46689b9f7fa2ebd9efceec626/sc2ts/utils.py#L402)

I think we want (for now)
- derived_state
- inherited_state
- num_descendants
- num_inheritors
- num_parents

We can assume for now that we have single-base alleles, and pull all the code needed for these from sc2ts.

Add some simple tests also to ``tests/test_data_model.py``

**Comment by savitakartik** [comment]
closed in PR #48
