### ISSUE TITLE
Edge explorer

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer-qc#42]
@duncanMR and I have discussed some options for how we'd make an explorer for edge data (based on the information in #40) analagous to the mutation explorer.

@duncanMR - can you update with some options that you've tried out please and maybe some screen shots

**Comment by duncanMR** [comment]
I will post edge visualisation screenshots once I have them working. The edges plot I made in #25 generates the data by tree traversal instead of using the edges table directly. Do you think it would be best to adapt it to find the immediate parents of a node by subsetting the edges dataframe?

**Comment by jeromekelleher** [comment]
These are different things I think - we're interested here in visualising **all** edges at once. E.g. we discussed having a native datashader type view in which each edge (rectangle in genome-time) overlapping with a given pixel increments that pixel by one. Maybe this isn't something that makes sense, but it's good to think about it anyway.

Plotting the ancestors for a specific node is different, and I'm not suer how that fits into the overall structure. It would be in a different "pane" to the full edge summary, anyway

**Comment by duncanMR** [comment]
I've struggled to plot the edges efficiently; the `hv.Path` function is very slow when there are too many lines. I've posted a question on the HoloViews discourse after having tried a few options: [https://discourse.holoviz.org/t/most-efficient-way-to-plot-thousands-of-horizontal-lines/5763](https://discourse.holoviz.org/t/most-efficient-way-to-plot-thousands-of-horizontal-lines/5763)
