### ISSUE TITLE
Colour mutations by number of descendants

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsinfer-qc#65]
In the mutations-by-time-and-position plot, it would be useful to colour the mutations by number of descendants. We only want this when single mutations are rendered as we zoom into the plot. We want to avoid colouring mutations in zoomed-out views where Datashader aggregation happens, as this wouldn't be as helpful (also we've found hue doesn't work well with Datashader).

**Comment by jeromekelleher** [comment]
This could be a really nice feature. I guess the transition between coloured points and datashaded aggregation could be jarring, but lets try it out and see.

**Comment by savitakartik** [comment]
completed in #70
