### ISSUE TITLE
disabling bokeh toolbar for histograms

### ISSUE THREAD

**Issue by savitakartik** [tskit-dev/tsinfer-qc#69]
We've decided to look at matplotlib for histograms in the panel app, since bokeh plots seem to grab the mouse in an annoying way. In some panels we'd want to display both matplotlib and bokeh plots, but I haven't figured out a way to mix both backends yet. As a workaround for now, perhaps we could have bokeh histograms with the entire toolbar disabled? For simple summary plots most default tools aren't particularly helpful anyway (e.g., pan, zoom, reset). 
We should be able to disable the bokeh toolbar like this:

`histogram = histogram.opts(toolbar=None,default_tools = [])`

Or if we want to retain the ability to save plots:
`histogram = histogram.opts(toolbar='right', default_tools = ['save'])`

We may want to adjust bin size as well but that's probably a different issue.

**Comment by savitakartik** [comment]
https://github.com/tskit-dev/tsinfer-qc/assets/25925005/b7506ae9-4040-4472-986d-93b303d9a4dc

**Comment by jeromekelleher** [comment]
I like it, nice idea! We can add the ability to save later if someone wants it, let's just get rid of the the toolbar initially.

**Comment by savitakartik** [comment]
completed in #73

**Comment by savitakartik** [comment]
complteed in #73
