### ISSUE TITLE
Plot and summarise the distribution of tree spans

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsinfer-qc#9]
```python
breakpoints = tinfo.ts.breakpoints(as_array=True)
spans = breakpoints[1:] - breakpoints[:-1]
```

- Need to trim first and last spans, as they're not informative
- plot the distribution of tree spans. Need to handle the fact that there's a huge difference in size, somehow. Crude first pass:

```python
spans = spans[1:-1]
plt.hist(spans, range(1, 50))
```

**Comment by savitakartik** [comment]
closed in #16
